pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Debug Workspace') {
    steps {
        echo "=== ROOT DIRECTORY ==="
        bat 'dir'

        echo "=== INSIDE Day-30_API ==="
        dir('Day-30_API') {
            bat 'dir'
        }
    }
}

        stage('Install Dependencies') {
            steps {
                dir('Day-30_API') {
                    bat 'npm install'
                    bat 'npx playwright install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Day-30_API') {
                    script {
                        def status = bat(script: 'npx playwright test', returnStatus: true)
                        if (status != 0) {
                            echo "Tests failed, but continuing..."
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Generating HTML reports...'

            publishHTML(target: [
                reportDir: 'Day-30_API/playwright-report',
                reportFiles: 'index.html',
                reportName: 'Playwright HTML Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])
        }
    }
}